#!/bin/sh

# Set up QEMU for cross compilation
apt -y update
apt -y --only-upgrade install docker-ee
apt -y install qemu-user-static
cp /usr/bin/qemu-*-static .
docker run --rm --privileged multiarch/qemu-user-static:register --reset
